// Mocks generated by Mockito 5.0.17 from annotations
// in interview_task/test/articles_listing_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:interview_task/product/features/news_listing/model/article.dart'
    as _i6;
import 'package:interview_task/product/features/news_listing/service/news_api_repository.dart'
    as _i3;
import 'package:interview_task/product/features/news_listing/service/news_service/api_failure.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [NewsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsRepository extends _i1.Mock implements _i3.NewsRepository {
  MockNewsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.ApiFailure, List<_i6.Article>>> fetch() =>
      (super.noSuchMethod(Invocation.method(#fetch, []),
              returnValue:
                  Future<_i2.Either<_i5.ApiFailure, List<_i6.Article>>>.value(
                      _FakeEither_0<_i5.ApiFailure, List<_i6.Article>>()))
          as _i4.Future<_i2.Either<_i5.ApiFailure, List<_i6.Article>>>);
}
